In [1]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
pseudo_inverse_matrix = np.linalg.pinv(matrix)

print("Pseudo-inverse of the matrix:")
print(pseudo_inverse_matrix)

Pseudo-inverse of the matrix:
[[-6.38888889e-01 -1.66666667e-01  3.05555556e-01]
 [-5.55555556e-02  3.46944695e-17  5.55555556e-02]
 [ 5.27777778e-01  1.66666667e-01 -1.94444444e-01]]


In [2]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)

print(eigenvectors)

[ 1.61168440e+01 -1.11684397e+00 -4.22209278e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [3]:
U, S, V = np.linalg.svd(matrix)
print(U)

print(S)

print(V)

[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
[1.68481034e+01 1.06836951e+00 4.41842475e-16]
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [4]:
vector = np.array([1, 2, 3])
norm = np.linalg.norm(vector)
print(norm)

3.7416573867739413
