In [1]:
import numpy as np

vector = np.array([1, 2, 3])

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [2]:
vector

array([1, 2, 3])

In [3]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
print(vector.shape)
print(matrix.shape)
print(matrix.shape[0])
print(matrix.shape[1])

(3,)
(3, 3)
3
3


In [5]:
print(vector[0])
print(matrix[1, 1])

print(vector[0:2])
print(matrix[0:2, 0:2])

1
5
[1 2]
[[1 2]
 [4 5]]


In [6]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
print(np.add(vector1, vector2))

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print(np.dot(matrix1, matrix2))

[5 7 9]
[[19 22]
 [43 50]]
