In [1]:
import numpy as np

vector = np.array([1, 2, 3])
scalar = 5
scaled_vector = scalar * vector
print("Scaled vector:", scaled_vector)

Scaled vector: [ 5 10 15]


In [2]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
transposed_matrix = matrix.T

print("Transposed matrix:\n", transposed_matrix)

Transposed matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [3]:
matrix_determinant = np.linalg.det(matrix)
print("Matrix determinant:", matrix_determinant)

Matrix determinant: 6.66133814775094e-16


In [4]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
solution = np.linalg.solve(A, b)
print("Solution of the linear system:", solution)

Solution of the linear system: [2. 3.]
